version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 12345
      MARIADB_DATABASE: chatbot
      MARIADB_USER: thuylinh
      MARIADB_PASSWORD: 191003
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
